apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-elastic-persistent
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 10Gi