apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: production
  labels:
    service: elasticsearch
spec:
  serviceName: discover-elasticsearch
  replicas: 1
  selector:
    matchLabels:
      service: elasticsearch
  template:
    metadata:
      labels:
        service: elasticsearch
    spec:
      initContainers:
        - name: increase-the-vm-max-map-count
          image: busybox
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
        - name: fix-the-volume-permission
          image: busybox
          command: [ "sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data" ]
          securityContext:
            privileged: true
          volumeMounts:
            - name: azure-elastic-persistent
              mountPath: /usr/share/elasticsearch/data

      containers:
        - name: elasticsearch
          image:  <docker image>
          resources:
            limits:
              cpu: 800m
              memory: 3Gi
            requests:
              cpu: 800m
              memory: 2Gi
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: tcp
          env:
            - name: cluster.name
              value: "demo-elk"
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: azure-elastic-persistent
              mountPath: /usr/share/elasticsearch/data
            - name: elk-configmap
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
      volumes:
        - name: elk-configmap
          configMap:
            name: elk-configmap
  volumeClaimTemplates:
    - metadata:
        name: azure-elastic-persistent
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-premium"
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: managed-premium
        resources:
          requests:
            storage: 20Gi




